version: '2'
services:
  sacloud-cputime:
    build:
      context: .
      args:
        quiet: "True"
    environment:
      - SACLOUD_ACCESS_TOKEN
      - SACLOUD_ACCESS_TOKEN_SECRET
      - SACLOUD_REGION
